### PR TITLE
Rewrite colander schema

### PR DESCRIPTION
**Pull request by surabujin**
I am propose modular interface to schema validation. It's interface and behaviour mostly compatible with existing schema validator.

But it use "clean" colander deserialisation call, so all existing hacks that emulate in incompatible way colander features are removed.

PS New interface allow add other schema validators.

### CODE REVIEW

**Comment by surabujin** [comment]
Depends from https://github.com/Pylons/colander/pull/241

**Comment by leplatrem** [comment]
Thanks a lot @surabujin!

I really like the fact to be able to validate the data with any library! It covers issue #274 (and stuff like https://github.com/mozilla-services/cliquet/issues/244). Plus it looks like you managed to write some backward compat stuff. Neat!

The diff is pretty huge to review,  did you write specific tests for the new code?

What do you think if you split the Colander usage refactor from the pluggability (based on #330)? Is that even possible?

Thanks again for this huge piece of work!

**Comment by surabujin** [comment]
I have not add any specific tests yet. I just reach first goal - make it pluggable, leave colander work to colander and make it as much as possible to previous API (it can be even more compatible, but I don't see a sense for it now).

Even if I can split this 2 change - make schemas pluggable and rewrite colander support, I can't make to work old colander validation code with proposed pluggable model. So one patch can't be used without another one.

**Comment by tisdall** [comment]
I like the idea of making the schema checking pluggable as there's been other requests for using other validation libraries already.  I'm having a little trouble understanding how this patch works, though...  Do you have any example code that you used to test when developing?

**Comment by surabujin** [comment]
@tisdall you want examples how other libraries can be integrated here? I don't have them yet.

I will update documentation, also I have a plan to add support of FormEncode.

**Comment by tisdall** [comment]
No, I was thinking more along the lines of examples of how this works with
existing colander schemas.

**Comment by surabujin** [comment]
Promised usage example: https://gist.github.com/surabujin/8109f55dd02b57c17fda

**Comment by leplatrem** [comment]
> Promised usage example

I like it, even though I wonder if we shouldn't get rid of those custom `location` parameters, as in #330 

> Depends from Pylons/colander#241

Unfortunately, the merge and release cycles of colander are very long. See for example the PR #206, which depends on https://github.com/Pylons/colander/pull/157. The PR was merged more than a year ago in colander, but never got released.

That's also why having pluggable schema libraries is a must-have! Projects like https://github.com/nicolaiarocci/cerberus or https://github.com/marshmallow-code/marshmallow are a lot more active and reactive!

Nevertheless, please be aware that we cannot merge so much new code without exhaustive and «specs» tests [1]. Especially because afterwards, we become the implicit maintainers of all this :)

Good luck and thank again for this excellent initiative :)

[1] : http://blog.mathieu-leplatre.info/your-tests-as-your-specs.html <br/> https://medium.com/javascript-scene/what-every-unit-test-needs-f6cd34d9836d

**Comment by lmctv** [comment]
While still not in a public release, Pylons/colander#241 have been merged

**Comment by leplatrem** [comment]
We took a different approach, see https://github.com/Cornices/cornice/blob/master/docs/source/upgrading.rst#colander-validation

**Pull request closed without merging**
