### PR TITLE
Add validators for querystring, path, and headers.

### PR DESCRIPTION
**Pull request by bowlofeggs**
Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Comment by bowlofeggs** [comment]
I'll take a look at the test failures soon, but it might take me a few days. I'm busy updating one of my apps to Cornice 3 from Cornice 1 (whew!)

**Comment by bowlofeggs** [comment]
@leplatrem Thanks for the approval!

What do you think about using ```six``` to resolve the metaclass differences between Python 2 and 3 for this patch?

Here's a change I'm applying to my patch that I think will get it to pass:

```
diff --git a/cornice/validators/_colander.py b/cornice/validators/_colander.py                                        
index 85fdb5f..0aa2305 100644                              
--- a/cornice/validators/_colander.py                      
+++ b/cornice/validators/_colander.py                      
@@ -5,6 +5,8 @@              
 import inspect              
 import warnings             
                             
+from six import with_metaclass                            
+                            
                             
 def _generate_colander_validator(location):               
     """                     
@@ -60,9 +62,10 @@ def _generate_colander_validator(location):                                                        
                 class_attrs[location] = _ensure_instantiated(schema)                                                 
                 return type(name, bases, class_attrs)     
                             
-        class RequestSchema(colander.MappingSchema):      
+        class RequestSchema(with_metaclass(               
+                RequestSchemaMeta, colander.MappingSchema)):                                                         
             """A schema to validate the request's location attributes."""                                            
-            __metaclass__ = RequestSchemaMeta             
+            pass            
                             
         validator(request, RequestSchema(), deserializer, **kwargs)                                                  
         request.validated = request.validated.get(location, {})                                                      
diff --git a/setup.py b/setup.py                           
index d406235..9af21d1 100755                              
--- a/setup.py               
+++ b/setup.py               
@@ -9,7 +9,7 @@ with open(os.path.join(here, 'README.rst')) as f:                                                     
 with open(os.path.join(here, 'CHANGES.txt')) as f:        
     CHANGES = f.read()      
                             
-requires = ['pyramid>=1.7',  'simplejson']                
+requires = ['pyramid>=1.7',  'simplejson', 'six']         
                             
 entry_points = ""           
 package_data = {}
```

**Comment by leplatrem** [comment]
> What do you think about using six to resolve the metaclass differences between Python 2 and 3 for this patch?

I don't have too much bandwidth lately, but otherwise I would be tempted to drop Python2 support :) 

Regarding `six` I have nothing against it, but if it's just for one helper, I believe we can put it inline in our utils instead of adding a new dependency. Looks it's rather small:
https://github.com/benjaminp/six/blob/63b2661b94463b59752396a3562c9e5ebe672f97/six.py#L819-L832

**Comment by leplatrem** [comment]
@Natim what do you think about inlining the metaclass helper instead of adding dependency to `six`?

**Comment by Natim** [comment]
What would be the benefit of doing that?

**Comment by leplatrem** [comment]
> What would be the benefit of doing that?

Avoid introducing a new dependency that does a thousand things for a 8 LOC function

**Comment by Natim** [comment]
I wouldn't be afraid about it, six is also most likely installed already.

**Pull request merged**
