### PR TITLE
Feature/changes in colander validation

### PR DESCRIPTION
**Pull request by czekan**
@leplatrem  I thought it is better to explicitly raise an error with a meaningful message rather than just fail with ValueError (on call ``request.validated.update(some_non_empty_list)``) when schema is not an instance of ``colander.MappingSchema``. What do you think? #503

### CODE REVIEW

**Comment by Rogalek** [comment]
I had the same issue in my app. I am going to borrow your fork after merging with current master and use in my code. Thanks.

**Comment by leplatrem** [comment]
My bad, I really missed this PR :(

**Comment by Rogalek** [comment]
so @leplatrem are you going to merge this?

**Comment by leplatrem** [comment]
I released 4.0 with this change

**Pull request merged**
