### PR TITLE
configurator: cornice should not commit configuration ever

### PR DESCRIPTION
**Pull request by ergo**
Fixes https://github.com/Cornices/cornice/issues/440, by removing commits and fixing tests with conflicting declarations.

### CODE REVIEW

**Comment by ergo** [comment]
Basicly if you do:

    @view_config('foo', renderer='foo')
    @view_config('foo', renderer='bar')
    def bar...

How pyramid is supposed to understand what renderer it should use? It need to distinguish request based on some condition. This is exactly why the test failed.

**Comment by leplatrem** [comment]
> How pyramid is supposed to understand what renderer it should use? It need to distinguish request based on some condition. This is exactly why the test failed.

Yes I get that, but I now wonder how it worked when we were doing the `config.commit()1`

**Comment by ergo** [comment]
I don't know, it should not be working to my knowledge. Maybe something swallowed the exception? (Btw. I'm online on #services-dev if you want to chat.

**Comment by leplatrem** [comment]
Fine, we should not be committing anyway, so let's trust the tests on this one :) 

Thanks!

**Pull request merged**
